### ISSUE TITLE
Missing resources

### ISSUE THREAD

**Issue by NoxiousPluK** [civitai/comfy-nodes#3]
I have my LoRA loaders set up like this:
![image](https://github.com/civitai/comfy-nodes/assets/4255780/381fb5f9-1b61-4a3f-a81b-92d8076791a8)

And the rest of my chain is pretty generic, like this:
![image](https://github.com/civitai/comfy-nodes/assets/4255780/b29a7151-2927-476c-b909-7902bd8831e9)

However on uploading the image, none of the used LoRA's get identified properly and I get this message on CivitAI.
I'm also not allowed to manually link resources:
![image](https://github.com/civitai/comfy-nodes/assets/4255780/a5bfa094-941e-4b93-9247-4f60e51f35c6)

**Comment by WASasquatch** [comment]
I don't believe detection of AIR tags from ComfyUI has been added yet. I do believe this is currently under the works though.

**Comment by NoxiousPluK** [comment]
Ah, apologies! I did read over the 'coming soon' part in the announcement. My bad! <3
