### ISSUE TITLE
ComfyUI metadata recoding

### ISSUE THREAD

**Issue by RangerFrank** [civitai/comfy-nodes#9]
Am I getting this right? The only way to record accurate image metadata for CivitAI using ComfyUI gens is to install these nodes, MANUALLY TRACK DOWN AND RECORD REFERENCE NUMBERS FROM EVERY RESOURCE FOR EVERY GEN EVERY SINGLE TIME YOU CHANGE THEM, install other third party custom nodes, link them all together using very specific intermediary nodes with very specific naming conventions for identification, only for it to not work anyway?

Does CivitAI have any plans to standardise resource recording for ComfyUI? Not much point in sharing if 90% of what's important isn't there, and I don't care how much of the workflow is saved to the image if nobody can use the information from it.

**Comment by WASasquatch** [comment]
This repo is for checkpoint loader, lora loader nodes, etc. It isn't involved with workflow scraping on CivitAI website for generations.

**Comment by RangerFrank** [comment]
Sounds like the project needs  a change of scope to remain relevant.
